#!/bin/bash
#programmer: rich powell
######################################################################
#the els program extends the ls -l command to include more file type 
#flags for various file extensions.                                               
######################################################################

# CUSTOM ERROR HANDLING
catchError(){
	printf "Error!\nTry els --help for Help\nTry els -? to see File Extensions\n"
}

# TEST FOR -l OPTION 
if (ls $* 2> /dev/null | tail -n 1 | awk '{print NF}' | grep -q "9") ; then 
	ls $* | awk '{ 
	
	switch ($NF) {
	# PRINT TOTAL LINE
	case /[0-9]$/:
		print $0
		break

	# (C) CLASS FILE
	case /[.]class$/:
		print $0 | "sed 's/^-/C/'"
		break 		

	# (F) SWIFT FILE
	case /[.]swift$/:
		print $0 | "sed 's/^-/F/'"
		break

	# (H) HTML FILE	
	case /[.]html$/:
		print $0 | "sed 's/^-/H/'"
		break

	# (J) JAVA FILE	
	case /[.]java$/:
		print $0 | "sed 's/^-/J/'"
		break

	# (K) KOTLIN FILE 	
	case /[.]kot$/:
		print $0 | "sed 's/^-/K/'"
		break

	# (P) PYTHON FILE
	case /[.]py$/:
		print $0 | "sed 's/^-/P/'"
		break

	# (X) XML FILE
	case /[.]xml$/:
		print $0 | "sed 's/^-/X/'"
		break

	# IGNORE HIDDEN FILES
	case /^[.]/:
		break

	default:
	# TEST IF THE FILE IS A SHELL SCRIPT
	if(system("file --mime-type -b " $NF "| grep -q 'text/x-shellscript'")==0)
		print $0 | "sed 's/^-/B/'"
  else
	 # ANY NON LISTED TYPES
	 print $0 				
													 
}
}
'
# -? SHOW ALL DEFINED FILES EXTENSIONS
elif [[  $1 == "-?" ]]; then
cat <<EOF
KNOWN FILE EXTENSTIONS
======================
B-SHELLSCRIPT
C-CLASS
F-SWIFT
H-HTML
J-JAVA
P-PYTHON
K-KOTLIN
X-XML
EOF

else 
	# EXECUTE ALL OTHER LS COMMANDS
	if (ls $* 2>/dev/null); then
		exit;	
	else
	# CATCH ANY ERRORS
		 catchError
	fi
fi
